stages:
  - deploy

pages:
  stage: deploy
  script:
    - npm install -g @angular/cli
    - npm install
    - ng build --prod
    - mv dist/[nom-du-projet] public
  artifacts:
    paths:
      - public
  only:
    - master
